package nl.rhaydus.pokedex.core.presentation.theme

import androidx.compose.ui.graphics.Color

val POKEDEX_RED = Color(0xFFFE5555)
val POKEDEX_GREEN = Color(0xFF8DDD8B)
val POKEDEX_ORANGE = Color(0xFFFFAE75)
val POKEDEX_BLUE = Color(0xFF93B9F7)

val POKEDEX_BACKGROUND = Color(0xFFF9F9F9)

val TYPE_NORMAL_COLOR = Color(0XFFA0A3A0)
val TYPE_FIRE_COLOR = Color(0XFFFFAE76)
val TYPE_FIGHTING_COLOR = Color(0XFFF07874)
val TYPE_WATER_COLOR = Color(0xFF93B9F6)
val TYPE_FLYING_COLOR = Color(0XFFCDB8F8)
val TYPE_GRASS_COLOR = Color(0XFF8DDC8B)
val TYPE_POISON_COLOR = Color(0XFFD584C6)
val TYPE_ELECTRIC_COLOR = Color(0XFFFED856)
val TYPE_GROUND_COLOR = Color(0XFFEEC770)
val TYPE_PSYCHIC_COLOR = Color(0XFFFE93B4)
val TYPE_ROCK_COLOR = Color(0XFFD8C17A)
val TYPE_ICE_COLOR = Color(0XFFAAE8E7)
val TYPE_BUG_COLOR = Color(0XFFC3D266)
val TYPE_DRAGON_COLOR = Color(0XFFB07EFE)
val TYPE_GHOST_COLOR = Color(0XFFAA92BF)
val TYPE_DARK_COLOR = Color(0XFFA89388)
val TYPE_STEEL_COLOR = Color(0XFF2096A3)
val TYPE_FAIRY_COLOR = Color(0XFFFFB1C1)